Update about us
AY2425S1-CS2103T-F08-1a/tp pull request #16
Opened 2024-09-26 15:16 UTC by Plishh

fix #14

2024-09-26 15:42 UTC, Jollybomber requested changes

2024-09-26 15:42 UTC, Jollybomber commented on docs/AboutUs.md
> +<img src="imgaes/plishh.png" width="200px">
```suggestion
<img src="images/plishh.png" width="200px">
```

2024-09-26 15:52 UTC, Plishh commented on docs/AboutUs.md
> +<img src="imgaes/plishh.png" width="200px">
changed

2024-10-03 15:28 UTC, Jollybomber approved these changes
LGTM

2024-10-04 00:02 UTC, mingyang143 commented
Resolve merge conflicts thanks.

2024-10-04 02:36 UTC, merged